// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using tim_BackendTest_MidLevel.Models;

namespace tim_BackendTest_MidLevel.Models
{
    public partial class Myoffice_ACPDContext
    {
        private IMyoffice_ACPDContextProcedures _procedures;

        public virtual IMyoffice_ACPDContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new Myoffice_ACPDContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IMyoffice_ACPDContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class Myoffice_ACPDContextProcedures : IMyoffice_ACPDContextProcedures
    {
        private readonly Myoffice_ACPDContext _context;

        public Myoffice_ACPDContextProcedures(Myoffice_ACPDContext context)
        {
            _context = context;
        }

        public virtual async Task<int> NEWSIDAsync(string tableName, OutputParameter<string> returnSID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterReturnSID = new SqlParameter
            {
                ParameterName = "ReturnSID",
                Size = 40,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = returnSID?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.NVarChar,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "TableName",
                    Size = 256,
                    Value = tableName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterReturnSID,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[NEWSID] @TableName = @TableName, @ReturnSID = @ReturnSID OUTPUT", sqlParameters, cancellationToken);

            returnSID?.SetValue(parameterReturnSID.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
